env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
settings:
  jest: { version: 26 }
plugins: ['jest']
extends: ['eslint:recommended', 'plugin:jest/recommended']
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  {
    jest/no-disabled-tests: 'warn',
    jest/no-focused-tests: 'error',
    jest/no-identical-title: 'error',
    jest/prefer-to-have-length: 'warn',
    jest/valid-expect: 'error',
    jest/no-try-expect: 'off',
    jest/no-conditional-expect: 'off',
  }
